config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources replaces all CRUD actions. I've kept them below for legacy. Details:
  # https://guides.rubyonrails.org/routing.html#resource-routing-the-rails-default
  # https://riptutorial.com/ruby-on-rails/example/1080/resource-routing--basic-
  resources :tasks

  # legacy tasks before refactoring
  # # create a new restaurant - show the new restaurant form
  # # The `new` route needs to be *before* `show` route.
  # get "tasks/new", to: "tasks#new"

  # # add a new restaurant - submit the data
  # post "tasks", to: "tasks#create"

  # # show all tasks
  # get "tasks", to: "tasks#index"

  # # show one task
  # get "tasks/:id", to: "tasks#show", as: :task

  # # edit an existing task step 1: display the existing task in fields
  # get "tasks/:id/edit", to: "tasks#edit", as: :edit

  # # edit an existing task step 2, patch in the new data
  # patch "tasks/:id", to: "tasks#update"

  # # destroy a task
  # delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def show
    get_task
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # no need for app/views/restaurants/create.html.erb
    redirect_to tasks_path
  end

  def edit
    get_task
  end

  def update
    get_task
    @task.update(task_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    # We need to use Strong Params again to avoid this error, see private
    # method below

    # no need for app/views/restaurants/update.html.erb
    redirect_to tasks_path
  end

  def destroy
    get_task
    @task.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def get_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://use.fontawesome.com/64a2f0be1d.js"></script>
    <title>Task Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit A Task</h1>

<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

<%= link_to("Back to Task List", tasks_path) %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<!-- fontawesome icons weren't displaying correctly,
followed steps here to fix it https://stackoverflow.com/questions/37092384/rails-font-awesome-icons-not-showing-using-font-awesome-rails-gem -->
<ul>
  <% @tasks.each do |task| %>
    <li>
    <% if task.completed %>
      <i class="fa-solid fa-check"></i>
    <% else %>
      <i class="fa-regular fa-square"></i>
    <% end %>



    <%= link_to task.title, task_path(task) %> | <%= link_to "Delete",
            task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>



 <button type="button" class="btn btn-default"><%= link_to("Create New Task", new_task_path) %></button>

app/views/tasks/new.html.erb
<h1>Add A New Task</h1>

<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

 <button type="button" class="btn btn-default">
 <%= link_to("Back to Task List", tasks_path) %>
 </button>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>


<p>  Done? <% if @task.completed %>
      <i class="fa-solid fa-check"></i>
    <% else %>
      <i class="fa-regular fa-square"></i>
    <% end %></p>


<%= link_to("Edit Task", edit_task_path) %>
<%= link_to("Back to Task List", tasks_path) %>